source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/myiOSComponent/myRepo.git'
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'TKDataAnalysisCategory_Example' do
  pod 'TKDataAnalysisCategory', :path => '../'

  target 'TKDataAnalysisCategory_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
    pod 'TKDataAnalysis', '~> 0.0.1'
  end
end
