use_frameworks!

target 'TKDataAnalysisCategory_Example' do
  pod 'TKDataAnalysisCategory', :path => '../'

  target 'TKDataAnalysisCategory_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
